# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# General config used promptwide
add_newline = false 
palette = 'pastel'

# only removes time and battery
format = """
$username\
$hostname\
$shlvl\
$singularity\
$kubernetes\
$directory\
$vcsh\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
$docker_context\
$package\
$c\
$cmake\
$cobol\
$daml\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$golang\
$guix_shell\
$haskell\
$haxe\
$helm\
$java\
$julia\
$kotlin\
$lua\
$nim\
$nodejs\
$ocaml\
$opa\
$perl\
$php\
$pulumi\
$purescript\
$python\
$raku\
$rlang\
$red\
$ruby\
$rust\
$scala\
$swift\
$terraform\
$vlang\
$vagrant\
$zig\
$buf\
$nix_shell\
$conda\
$meson\
$spack\
$memory_usage\
$aws\
$gcloud\
$openstack\
$azure\
$env_var\
$crystal\
$custom\
$sudo\
$cmd_duration\
$line_break\
$jobs\
$status\
$container\
$shell\
$character"""

[battery]
disabled = true

[c] # try to also detect c++ in the c module
detect_extensions = ['c', 'h', 'cpp', 'c++', 'cc']
commands = [ [ 'cc', '--version' ], [ 'gcc', '--version' ], [ 'clang', '--version' ], ['g++', '--version' ] ]
style = 'light-orange'

[character] 
success_symbol = '[➜](bold green)'
error_symbol = '[➜](bold dim-red)'

[cmd_duration] # only show notif after process took more than a minute
show_notifications = true
min_time_to_notify = 60_000
style = 'bold light-cyan'

[container]
style = 'bold dim-red'

[directory]
style = 'bold underline violet'
read_only_style = 'dim-pink'

[docker_context]
style = 'bold dim-blue'

[env_var]
style = 'italic grey'

[fill]
style = 'bold dim-grey'

[git_branch]
style = 'bold light-orange'

[git_commit]
style = 'bold cyan'

[git_metrics]
disabled = false
added_style = 'bold light-cyan'
deleted_style = 'bold dim-red'

[hostname]
style = 'bold grey'

[localip]
disabled = true

[package]
style = 'fg:bold light-grey bg:light-blue' 

[python] # don't trigger on requirements.txt
detect_files = ['.python-version', 'Pipfile', '__init__.py', 'pyproject.toml', 'setup.py', 'tox.ini']
style = 'bold light-orange'

[status]
format = '[$symbol [$common_meaning](italic underline dim-beige) \[$status\]]($style) '
disabled = false
style = 'bold dim-red'

[time]
format = '[$time]($style)'
disabled = false
style = 'bold beige'

[username]
show_always = true
format = '[$user]($style) in '
style_root = 'italic bold pink' 

[palettes.pastel]
# ================[neutrals]============
white = '#f9f7f7'
gray = '#878384'
grey = '#878384'
black = '#33333b'
light-white = '#f9fafd'
light-gray = '#a3a6a3'
light-grey = '#a3a6a3'
light-black = '#3b3638'
dim-white = '#fff6ea'
dim-gray = '#5a5b5b'
dim-grey = '#5a5b5b'
# ================[reds]================
pink = '#fabec0'
red = '#ef3a5d'
orange = '#ff8210'
light-pink = '#eed7db'
light-red = '#f63e7b'
light-orange = '#ffca7b'
dim-pink = '#dc7684'
dim-red = '#de0f3f'
dim-orange = '#da6220'
# ================[blues]===============
cyan = '#4aadaa'
blue = '#88a9c3'
violet = '#d39aff'
light-cyan = '#9bd3cb'
light-blue = '#a4c9d7'
light-violet = '#d2c7ff'
dim-cyan = '#43727a'
dim-blue = '#2d7f9d'
dim-violet = '#945acb'
# ================[greens]==============
lime = '#6ac66b'
green = '#81b673'
turquoise = '#129a7d'
light-lime = '#a6d79b'
light-green = '#8cb89f'
light-turquoise = '#61c2a2'
dim-lime = '#3bab5a'
dim-green = '#5f8368'
dim-turquoise = '#39827a'
# ================[yellows]=============
yellow = '#ffeb5b'
beige = '#e4ca99'
brown = '#a44f30'
light-yellow = '#fff9c7'
light-beige = '#f0df93'
light-brown = '#ac663e'
dim-yellow = '#f71e35'
dim-beige = '#c99a5b'
dim-brown = '#6d412a'
